### ISSUE TITLE
Tab writes * every time I press

### ISSUE THREAD

**Issue by phederal** [yCodeTech/auto-comment-blocks#2]
I write code in Typescript, for example, and Tab instead of tabulation writes " * " on each line

Version 1.1.0 от 2024-12-22

**Comment by yCodeTech** [comment]
@phederal I cannot replicate this. I use TS for the extension, and pressing `Tab` behaves as normal in both my working files, and the self-contained extension test environment.

Does it happen when inside a comment or outside?

Which operating system are you using?

Just to make sure it's the extension producing the issue, can you disable all extensions and see if it behaves normally? If it does, can you then only reactivate this extension and see if the issue comes back?

**Comment by yCodeTech** [comment]
I believe this to be fixed in the new release of v1.1.2. Please update the extension. If you're still having the same issue after updating, please reopen this issue and tell me more about the issue, and answering the questions in the above comment.
